[default]
locale = 'en-us'
extend-ignore-re = [
  "(?Rm)^.*(<!--|#|//)\\s*spellchecker:disable-line(-->|\n)?$",
  "(?s)(<!--|#|//)\\s*spellchecker:off\\s*(-->|\n).*?(<!--|#|//)\\s*spellchecker:on",
]
exclude = ["examples"]

[default.extend-words]
Jeongho = "Jeongho"
Nam = "Nam"
typia = "typia"
nestia = "nestia"