name: website
on: 
  push: 
    branches:
      - master
    paths:
      - README.md
      - 'src/**'
      - 'website/**'
      - 'package.json'
jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build TypeDoc
        run: |
          pnpm run typedoc 
          pnpm run typedoc -- --json website/public/api/openapi.json
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: ./website/public
